# Generated by Django 5.0.6 on 2024-06-20 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sriagapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Userss',
        ),
    ]
