# Generated by Django 5.0.6 on 2024-06-20 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sriagapp', '0002_rename_users_userss'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userss',
            new_name='User',
        ),
    ]
