# Generated by Django 5.0.6 on 2024-06-21 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sriagapp', '0003_rename_userss_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
